### ISSUE TITLE
authentication problem

### ISSUE THREAD

**Issue by cordoval** [church/thechurch#34] opened 2015-04-03 07:48 UTC
@davidbarratt re https://github.com/symfony/symfony/issues/13628
I installed it and went through the registration process. The first form sends you an email url, then you proceed to register yourself progressively but the authentication does not happen until later, not sure even later. Seeing your CodeAuthenticator is a bit confusing and probable is there where the error happens. Have you checked?

nice app btw :older_man:

**Comment by davidbarratt** [comment] 2015-04-03 10:35
@cordoval 

I followed the instructions here:
http://symfony.com/doc/current/cookbook/security/api_key_authentication.html#only-authenticating-for-certain-urls
to only authenticate on certain urls, and you see this code here:
https://github.com/church/thechurch/blob/develop/src/Church/Security/CodeAuthenticator.php#L39-L46
and here are the routes:
https://github.com/church/thechurch/blob/develop/src/Church/Controller/UserController.php#L120-L123
and
https://github.com/church/thechurch/blob/develop/src/Church/Controller/UserController.php#L145-L148

I'm actually authenticating you as soon as you click the link in the email (or put the code into the web form). However, Symfony does not show you as authenticated at all. As you go through the registration process, I'm just changing your user role:
https://github.com/church/thechurch/blob/develop/src/Church/Entity/User/User.php#L169-L206
so if you are able to proceed to the next steps, you were successfully authenticated.

If you'd like to see the bug in symfony/symfony#13628 go to the form and put in an email address, then (before verifying the code by clicking the link or inputing the code in the form), add a `username` in the database. Then click the link in the email and Symfony will show you as authenticated. You're authenticated either way, just without the username Symfony will not show it.

I'll double check all this when I get home later. :)

**Comment by davidbarratt** [comment] 2015-04-03 10:36
and thanks for the compliment! I have a lot of work left, but it's coming along.

**Comment by davidbarratt** [comment] 2015-04-04 01:44
@cordoval,

I can confirm that this works and is correct. Symfony just doesn't show you as being authenticated unless you have a username in the database before authenticating.

**Comment by cordoval** [comment] 2015-04-04 02:51
I will dig deeper a little soon to confirm for myself. Feel free to pair program perhaps tomorrow or monday night on this project I like it. :+1:

**Comment by davidbarratt** [comment] 2016-12-31 19:22
closing since symfony/symfony#13628 is closed. :)

**Closed by davidbarratt** 2016-12-31 19:22 UTC
Labels: bug
